"""Core domain entities -- the ground truth the whole system is built around.

These are the persisted entities (§38), shared between the dataset generator
that creates them and the seeder that loads them into Postgres. Keeping one
definition means the generator cannot emit something the database cannot hold.

The modelling rule that must not be broken (§39): a Parcel NEVER carries an
owner name. Ownership is always expressed through time-bounded OwnershipRecord
rows, which is what makes "who owned this in 1998?" answerable at all.
"""

from __future__ import annotations

from datetime import date
from fractions import Fraction

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from .enums import AreaUnit, DocumentType, MutationType, Role


class Location(BaseModel):
    """A node in the administrative hierarchy (§11).

    India > State > District > Tehsil > Village. Modelled as one self-
    referencing table rather than four, so jurisdiction checks for officers
    are a single ancestor query.
    """

    model_config = ConfigDict(extra="forbid")

    location_id: str
    name: str
    name_devanagari: str | None = None
    level: str = Field(pattern="^(STATE|DISTRICT|TEHSIL|VILLAGE)$")
    parent_id: str | None = None


class Owner(BaseModel):
    """A person who can hold land.

    Distinct from User: an Owner may exist in the records with no login, and a
    citizen User is linked to exactly one Owner via their CitizenProfile.
    """

    model_config = ConfigDict(extra="forbid")

    owner_id: str
    name: str
    guardian_name: str | None = None
    is_synthetic: bool = True


class Parcel(BaseModel):
    """A cadastral plot -- the entity everything else hangs off (§11)."""

    model_config = ConfigDict(extra="forbid")

    parcel_id: str
    village_id: str
    khasra_number: str
    khata_number: str | None = None
    area_value: float = Field(gt=0)
    area_unit: AreaUnit
    area_unit_raw: str | None = None
    land_class: str | None = None
    #: WKT polygon, EPSG:4326. Generated by services/gis (§53).
    geometry_wkt: str | None = None
    is_synthetic: bool = True


class OwnershipRecord(BaseModel):
    """A time-bounded ownership interest (§39).

    `valid_to = None` means "current". `share` is kept as a fraction string
    because rounding a recorded share to a float would corrupt its legal
    meaning.
    """

    model_config = ConfigDict(extra="forbid")

    ownership_id: str
    owner_id: str
    parcel_id: str
    share: str = "1/1"
    valid_from: date
    valid_to: date | None = None
    #: The mutation that created this interest. None for the opening record.
    mutation_id: str | None = None
    status: str = "ACTIVE"

    @field_validator("share")
    @classmethod
    def _share_is_a_sane_fraction(cls, v: str) -> str:
        try:
            frac = Fraction(v)
        except (ValueError, ZeroDivisionError) as exc:
            raise ValueError(f"share {v!r} is not a valid fraction") from exc
        if not (0 < frac <= 1):
            raise ValueError(f"share {v!r} must be in (0, 1]")
        return v

    @model_validator(mode="after")
    def _dates_ordered(self) -> OwnershipRecord:
        if self.valid_to is not None and self.valid_to < self.valid_from:
            raise ValueError(
                f"ownership {self.ownership_id}: valid_to {self.valid_to} "
                f"precedes valid_from {self.valid_from}"
            )
        return self

    @property
    def share_fraction(self) -> Fraction:
        return Fraction(self.share)

    def covers(self, on: date) -> bool:
        """True if this interest was in force on `on`."""
        if on < self.valid_from:
            return False
        return self.valid_to is None or on <= self.valid_to


class Mutation(BaseModel):
    """A recorded change of ownership (§40)."""

    model_config = ConfigDict(extra="forbid")

    mutation_id: str
    parcel_id: str
    mutation_number: str
    mutation_type: MutationType
    effective_date: date
    registration_date: date | None = None
    previous_owner_ids: list[str] = Field(default_factory=list)
    new_owner_ids: list[str] = Field(default_factory=list)
    source_document_id: str | None = None
    status: str = "REGISTERED"


class LandRecord(BaseModel):
    """A record-of-rights style row tying a parcel to a record year."""

    model_config = ConfigDict(extra="forbid")

    record_id: str
    parcel_id: str
    document_type: DocumentType
    record_year: str
    is_synthetic: bool = True


class SyntheticUser(BaseModel):
    """A demo login (§46).

    Citizens carry an `owner_id`; officers carry a `jurisdiction_id` naming the
    highest location they may act within (§36).
    """

    model_config = ConfigDict(extra="forbid")

    user_id: str
    role: Role
    name: str
    email: str
    owner_id: str | None = None
    jurisdiction_id: str | None = None

    @model_validator(mode="after")
    def _role_shape(self) -> SyntheticUser:
        if self.role is Role.CITIZEN and not self.owner_id:
            raise ValueError(f"{self.user_id}: citizen must link to an owner_id")
        if self.role is not Role.CITIZEN and self.owner_id:
            raise ValueError(f"{self.user_id}: only citizens may link to an owner_id")
        if self.role is not Role.CITIZEN and not self.jurisdiction_id:
            raise ValueError(f"{self.user_id}: officer must have a jurisdiction_id")
        return self


class SyntheticWorld(BaseModel):
    """Everything the generator produces, in one loadable payload."""

    model_config = ConfigDict(extra="forbid")

    seed: int
    locations: list[Location] = Field(default_factory=list)
    owners: list[Owner] = Field(default_factory=list)
    parcels: list[Parcel] = Field(default_factory=list)
    ownership: list[OwnershipRecord] = Field(default_factory=list)
    mutations: list[Mutation] = Field(default_factory=list)
    land_records: list[LandRecord] = Field(default_factory=list)
    users: list[SyntheticUser] = Field(default_factory=list)

    def ownership_for(self, parcel_id: str, on: date) -> list[OwnershipRecord]:
        """Ownership interests in force for a parcel on a given date."""
        return [
            o for o in self.ownership if o.parcel_id == parcel_id and o.covers(on)
        ]

    def parcels_for_owner(self, owner_id: str, on: date) -> list[str]:
        """Parcel ids an owner held on a given date."""
        return sorted(
            {
                o.parcel_id
                for o in self.ownership
                if o.owner_id == owner_id and o.covers(on)
            }
        )
