"""initial schema

Revision ID: f67d310791a5
Revises: 
Create Date: 2026-08-31 18:39:24.554379
"""
from __future__ import annotations

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = 'f67d310791a5'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_devanagari', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name=op.f('fk_locations_parent_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('external_id', name=op.f('uq_locations_external_id'))
    )
    op.create_index(op.f('ix_locations_level'), 'locations', ['level'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('code', name=op.f('uq_model_versions_code'))
    )
    op.create_table('owners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners'))
    )
    op.create_index(op.f('ix_owners_external_id'), 'owners', ['external_id'], unique=True)
    op.create_index(op.f('ix_owners_name'), 'owners', ['name'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('parcels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('village_id', sa.String(length=36), nullable=False),
    sa.Column('khasra_number', sa.String(length=32), nullable=False),
    sa.Column('khata_number', sa.String(length=32), nullable=True),
    sa.Column('area_value', sa.Float(), nullable=False),
    sa.Column('area_unit', sa.String(length=16), nullable=False),
    sa.Column('area_unit_raw', sa.String(length=32), nullable=True),
    sa.Column('land_class', sa.String(length=64), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['locations.id'], name=op.f('fk_parcels_village_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcels'))
    )
    op.create_index(op.f('ix_parcels_external_id'), 'parcels', ['external_id'], unique=True)
    op.create_index(op.f('ix_parcels_khasra_number'), 'parcels', ['khasra_number'], unique=False)
    op.create_index(op.f('ix_parcels_khata_number'), 'parcels', ['khata_number'], unique=False)
    op.create_index(op.f('ix_parcels_village_id'), 'parcels', ['village_id'], unique=False)
    op.create_index('ix_parcels_village_khasra', 'parcels', ['village_id', 'khasra_number'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permissions_role_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['locations.id'], name=op.f('fk_users_jurisdiction_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('external_id', name=op.f('uq_users_external_id'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('event_hash', name=op.f('uq_audit_events_event_hash'))
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_sequence'), 'audit_events', ['sequence'], unique=True)
    op.create_table('citizen_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_citizen_profiles_owner_id_owners'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_citizen_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizen_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_citizen_profiles_user_id'))
    )
    op.create_index(op.f('ix_citizen_profiles_owner_id'), 'citizen_profiles', ['owner_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=True),
    sa.Column('village_id', sa.String(length=36), nullable=True),
    sa.Column('record_year', sa.String(length=16), nullable=True),
    sa.Column('declared_khasra', sa.String(length=32), nullable=True),
    sa.Column('declared_khata', sa.String(length=32), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_report', sa.JSON(), nullable=True),
    sa.Column('quality_recommendation', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_documents_parcel_id_parcels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['village_id'], ['locations.id'], name=op.f('fk_documents_village_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_documents_external_id'), 'documents', ['external_id'], unique=True)
    op.create_index(op.f('ix_documents_parcel_id'), 'documents', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_documents_state'), 'documents', ['state'], unique=False)
    op.create_index(op.f('ix_documents_village_id'), 'documents', ['village_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=True),
    sa.Column('village_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_embeddings_parcel_id_parcels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['locations.id'], name=op.f('fk_embeddings_village_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings'))
    )
    op.create_index(op.f('ix_embeddings_entity_id'), 'embeddings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_embeddings_entity_type'), 'embeddings', ['entity_type'], unique=False)
    op.create_index(op.f('ix_embeddings_parcel_id'), 'embeddings', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_embeddings_village_id'), 'embeddings', ['village_id'], unique=False)
    op.create_table('grievances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('raised_by_id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=True),
    sa.Column('issue_type', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('supporting_storage_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_grievances_parcel_id_parcels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], name=op.f('fk_grievances_raised_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grievances')),
    sa.UniqueConstraint('external_id', name=op.f('uq_grievances_external_id'))
    )
    op.create_index(op.f('ix_grievances_parcel_id'), 'grievances', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_grievances_raised_by_id'), 'grievances', ['raised_by_id'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_table('land_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('record_year', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_land_records_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_land_records')),
    sa.UniqueConstraint('external_id', name=op.f('uq_land_records_external_id'))
    )
    op.create_index(op.f('ix_land_records_parcel_id'), 'land_records', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_land_records_status'), 'land_records', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id'))
    )
    op.create_table('anomaly_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('parcel_id', sa.String(length=36), nullable=True),
    sa.Column('anomaly_type', sa.String(length=48), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_anomaly_flags_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_anomaly_flags_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomaly_flags'))
    )
    op.create_index(op.f('ix_anomaly_flags_anomaly_type'), 'anomaly_flags', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomaly_flags_document_id'), 'anomaly_flags', ['document_id'], unique=False)
    op.create_index(op.f('ix_anomaly_flags_parcel_id'), 'anomaly_flags', ['parcel_id'], unique=False)
    op.create_table('approval_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_approval_actions_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_approval_actions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_actions'))
    )
    op.create_index(op.f('ix_approval_actions_decision'), 'approval_actions', ['decision'], unique=False)
    op.create_index(op.f('ix_approval_actions_document_id'), 'approval_actions', ['document_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('enhanced_storage_key', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages'))
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index('uq_page_per_document', 'document_pages', ['document_id', 'page_number'], unique=True)
    op.create_table('extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('layout_confidence', sa.Float(), nullable=True),
    sa.Column('validation_confidence', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON(), nullable=True),
    sa.Column('bbox_x1', sa.Integer(), nullable=True),
    sa.Column('bbox_y1', sa.Integer(), nullable=True),
    sa.Column('bbox_x2', sa.Integer(), nullable=True),
    sa.Column('bbox_y2', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_extractions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extractions'))
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_extractions_field'), 'extractions', ['field'], unique=False)
    op.create_index(op.f('ix_extractions_status'), 'extractions', ['status'], unique=False)
    op.create_table('mutations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('mutation_number', sa.String(length=32), nullable=False),
    sa.Column('mutation_type', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_mutations_parcel_id_parcels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_mutations_source_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mutations')),
    sa.UniqueConstraint('external_id', name=op.f('uq_mutations_external_id'))
    )
    op.create_index(op.f('ix_mutations_effective_date'), 'mutations', ['effective_date'], unique=False)
    op.create_index(op.f('ix_mutations_parcel_id'), 'mutations', ['parcel_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_processing_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_celery_task_id'), 'processing_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('validation_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_validation_findings_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_findings'))
    )
    op.create_index(op.f('ix_validation_findings_document_id'), 'validation_findings', ['document_id'], unique=False)
    op.create_index(op.f('ix_validation_findings_rule'), 'validation_findings', ['rule'], unique=False)
    op.create_table('verification_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('lowest_confidence', sa.Float(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_verification_tasks_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_verification_tasks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_tasks'))
    )
    op.create_index(op.f('ix_verification_tasks_assigned_to_id'), 'verification_tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_verification_tasks_document_id'), 'verification_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_verification_tasks_lowest_confidence'), 'verification_tasks', ['lowest_confidence'], unique=False)
    op.create_index(op.f('ix_verification_tasks_status'), 'verification_tasks', ['status'], unique=False)
    op.create_table('field_corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('model_prediction', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('confidence_at_correction', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('corrected_by_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_retraining_candidate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_id'], ['users.id'], name=op.f('fk_field_corrections_corrected_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_field_corrections_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], name=op.f('fk_field_corrections_extraction_id_extractions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_corrections'))
    )
    op.create_index(op.f('ix_field_corrections_document_id'), 'field_corrections', ['document_id'], unique=False)
    op.create_index(op.f('ix_field_corrections_extraction_id'), 'field_corrections', ['extraction_id'], unique=False)
    op.create_table('ocr_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Integer(), nullable=False),
    sa.Column('bbox_y1', sa.Integer(), nullable=False),
    sa.Column('bbox_x2', sa.Integer(), nullable=False),
    sa.Column('bbox_y2', sa.Integer(), nullable=False),
    sa.Column('script', sa.String(length=32), nullable=True),
    sa.Column('reading_order', sa.Integer(), nullable=True),
    sa.Column('is_handwritten', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], name=op.f('fk_ocr_blocks_page_id_document_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_blocks'))
    )
    op.create_index(op.f('ix_ocr_blocks_page_id'), 'ocr_blocks', ['page_id'], unique=False)
    op.create_table('ownership_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('mutation_id', sa.String(length=36), nullable=True),
    sa.Column('share', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mutation_id'], ['mutations.id'], name=op.f('fk_ownership_records_mutation_id_mutations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_ownership_records_owner_id_owners'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_ownership_records_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ownership_records')),
    sa.UniqueConstraint('external_id', name=op.f('uq_ownership_records_external_id'))
    )
    op.create_index('ix_ownership_owner_validity', 'ownership_records', ['owner_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_ownership_parcel_validity', 'ownership_records', ['parcel_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index(op.f('ix_ownership_records_owner_id'), 'ownership_records', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ownership_records_parcel_id'), 'ownership_records', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_ownership_records_valid_from'), 'ownership_records', ['valid_from'], unique=False)
    op.create_index(op.f('ix_ownership_records_valid_to'), 'ownership_records', ['valid_to'], unique=False)
    op.create_table('verification_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_verification_actions_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['verification_tasks.id'], name=op.f('fk_verification_actions_task_id_verification_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_actions'))
    )
    op.create_index(op.f('ix_verification_actions_task_id'), 'verification_actions', ['task_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correction_id', sa.String(length=36), nullable=True),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('selection_reason', sa.String(length=64), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('included_in_dataset', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['correction_id'], ['field_corrections.id'], name=op.f('fk_ai_feedback_correction_id_field_corrections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback'))
    )
    op.create_index(op.f('ix_ai_feedback_correction_id'), 'ai_feedback', ['correction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_feedback_correction_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_verification_actions_task_id'), table_name='verification_actions')
    op.drop_table('verification_actions')
    op.drop_index(op.f('ix_ownership_records_valid_to'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_valid_from'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_parcel_id'), table_name='ownership_records')
    op.drop_index(op.f('ix_ownership_records_owner_id'), table_name='ownership_records')
    op.drop_index('ix_ownership_parcel_validity', table_name='ownership_records')
    op.drop_index('ix_ownership_owner_validity', table_name='ownership_records')
    op.drop_table('ownership_records')
    op.drop_index(op.f('ix_ocr_blocks_page_id'), table_name='ocr_blocks')
    op.drop_table('ocr_blocks')
    op.drop_index(op.f('ix_field_corrections_extraction_id'), table_name='field_corrections')
    op.drop_index(op.f('ix_field_corrections_document_id'), table_name='field_corrections')
    op.drop_table('field_corrections')
    op.drop_index(op.f('ix_verification_tasks_status'), table_name='verification_tasks')
    op.drop_index(op.f('ix_verification_tasks_lowest_confidence'), table_name='verification_tasks')
    op.drop_index(op.f('ix_verification_tasks_document_id'), table_name='verification_tasks')
    op.drop_index(op.f('ix_verification_tasks_assigned_to_id'), table_name='verification_tasks')
    op.drop_table('verification_tasks')
    op.drop_index(op.f('ix_validation_findings_rule'), table_name='validation_findings')
    op.drop_index(op.f('ix_validation_findings_document_id'), table_name='validation_findings')
    op.drop_table('validation_findings')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_celery_task_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_mutations_parcel_id'), table_name='mutations')
    op.drop_index(op.f('ix_mutations_effective_date'), table_name='mutations')
    op.drop_table('mutations')
    op.drop_index(op.f('ix_extractions_status'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_field'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index('uq_page_per_document', table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_approval_actions_document_id'), table_name='approval_actions')
    op.drop_index(op.f('ix_approval_actions_decision'), table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_index(op.f('ix_anomaly_flags_parcel_id'), table_name='anomaly_flags')
    op.drop_index(op.f('ix_anomaly_flags_document_id'), table_name='anomaly_flags')
    op.drop_index(op.f('ix_anomaly_flags_anomaly_type'), table_name='anomaly_flags')
    op.drop_table('anomaly_flags')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_land_records_status'), table_name='land_records')
    op.drop_index(op.f('ix_land_records_parcel_id'), table_name='land_records')
    op.drop_table('land_records')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_raised_by_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_parcel_id'), table_name='grievances')
    op.drop_table('grievances')
    op.drop_index(op.f('ix_embeddings_village_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_parcel_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_entity_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_entity_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_documents_village_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_state'), table_name='documents')
    op.drop_index(op.f('ix_documents_parcel_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_external_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_citizen_profiles_owner_id'), table_name='citizen_profiles')
    op.drop_table('citizen_profiles')
    op.drop_index(op.f('ix_audit_events_sequence'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index('ix_parcels_village_khasra', table_name='parcels')
    op.drop_index(op.f('ix_parcels_village_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_khata_number'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_khasra_number'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_external_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_owners_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_external_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_level'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
